# Generated by Django 4.2.5 on 2023-12-06 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0008_rename_group_subject_groups'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='user',
            new_name='owner',
        ),
    ]
