# Generated by Django 4.2.5 on 2023-12-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0012_alter_lesson_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='name',
        ),
        migrations.AddField(
            model_name='group',
            name='number',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
