# Generated by Django 4.2.5 on 2023-12-15 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0013_remove_group_name_group_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='owner',
        ),
    ]
