# Generated by Django 4.2.5 on 2023-12-15 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('study', '0014_remove_group_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='owner',
        ),
        migrations.CreateModel(
            name='TeacherGroupSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='study.subject')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='study.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Дисциплина группы',
                'verbose_name_plural': 'Дисциплины групп',
            },
        ),
    ]
