# Generated by Django 4.2.5 on 2023-12-15 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0015_remove_subject_groups_remove_subject_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachergroupsubject',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='study.group'),
        ),
    ]
