# Generated by Django 4.2.5 on 2023-12-16 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0016_alter_teachergroupsubject_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='video',
        ),
        migrations.RemoveField(
            model_name='lessonphoto',
            name='name',
        ),
        migrations.RemoveField(
            model_name='lessonphoto',
            name='owner',
        ),
        migrations.AddField(
            model_name='lesson',
            name='type',
            field=models.CharField(choices=[('LC', 'Лекция'), ('PR', 'Практическое занятия'), ('LR', 'Лабораторное занятие')], default=1, max_length=32, verbose_name='Тип'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessonphoto',
            name='lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='study.lesson'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='study.teachergroupsubject'),
        ),
        migrations.CreateModel(
            name='LessonVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='lessons/videos/')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='study.lesson')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
    ]
