# Generated by Django 4.2.5 on 2023-12-17 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0017_remove_lesson_photos_remove_lesson_video_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='owner',
        ),
    ]
