# Generated by Django 4.2.5 on 2023-12-17 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0018_remove_test_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='test',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='study.test'),
        ),
    ]
