# Generated by Django 4.2.5 on 2023-12-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0019_alter_lesson_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('TX', 'Текстовый'), ('CH', 'С вариантами ответа')], max_length=32, verbose_name='Тип'),
        ),
    ]
