# Generated by Django 4.2.5 on 2023-12-17 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0021_try_need_check_studentanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='student_try',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students_answers', to='study.try'),
        ),
    ]
