# Generated by Django 4.2.5 on 2023-12-18 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('study', '0023_lessonfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='type',
            field=models.CharField(choices=[('LC', 'Лекция'), ('PR', 'Практическое занятия'), ('LR', 'Лабораторное занятие'), ('CW', 'Контрольная работа'), ('IW', 'Индивидуальное практическое занятие')], max_length=32, verbose_name='Тип'),
        ),
        migrations.CreateModel(
            name='StudentIndividualWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='lessons/students-works/')),
                ('score', models.IntegerField(blank=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_works', to='study.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_works', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Работа стундента',
                'verbose_name_plural': 'Работы студентов',
            },
        ),
    ]
