# Generated by Django 4.2.5 on 2023-12-18 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0024_alter_lesson_type_studentindividualwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
