# Generated by Django 4.2.5 on 2023-12-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_group_id_application_group_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='group_number',
            field=models.CharField(max_length=32),
        ),
    ]
